#!/bin/bash
# Daily Immune System Report Generator
# Run by Alex at end of each day (23:00 TRT)
# Sends report to Can

REPORT_FILE="/tmp/immune-system-daily-report-$(date +%Y%m%d).txt"
LOG_DIR="/home/ubuntu/.openclaw/workspace/agent-agency/immune-system/logs"

echo "🛡️ DAILY IMMUNE SYSTEM REPORT" > "$REPORT_FILE"
echo "Date: $(date '+%Y-%m-%d %H:%M TRT')" >> "$REPORT_FILE"
echo "Generated by: Alex (Immune System)" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "========================================" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# 1. Security Events
echo "🔒 SECURITY EVENTS" >> "$REPORT_FILE"
echo "------------------" >> "$REPORT_FILE"
if [ -f "$LOG_DIR/security-events.log" ]; then
    TODAY=$(date +%Y-%m-%d)
    EVENTS=$(grep "$TODAY" "$LOG_DIR/security-events.log" 2>/dev/null | wc -l)
    if [ "$EVENTS" -gt 0 ]; then
        echo "Events today: $EVENTS" >> "$REPORT_FILE"
        grep "$TODAY" "$LOG_DIR/security-events.log" 2>/dev/null | tail -5 >> "$REPORT_FILE"
    else
        echo "No security events today." >> "$REPORT_FILE"
    fi
else
    echo "No security events logged." >> "$REPORT_FILE"
fi
echo "" >> "$REPORT_FILE"

# 2. Policy Enforcement
echo "📋 POLICY ENFORCEMENT" >> "$REPORT_FILE"
echo "---------------------" >> "$REPORT_FILE"
if [ -f "$LOG_DIR/blocked-actions.log" ]; then
    TODAY=$(date +%Y-%m-%d)
    BLOCKED=$(grep "$TODAY" "$LOG_DIR/blocked-actions.log" 2>/dev/null | wc -l)
    echo "Actions blocked today: $BLOCKED" >> "$REPORT_FILE"
    if [ "$BLOCKED" -gt 0 ]; then
        echo "Recent blocks:" >> "$REPORT_FILE"
        grep "$TODAY" "$LOG_DIR/blocked-actions.log" 2>/dev/null | tail -3 >> "$REPORT_FILE"
    fi
else
    echo "No actions blocked today." >> "$REPORT_FILE"
fi
echo "" >> "$REPORT_FILE"

# 3. Disk Space Management
echo "💾 DISK SPACE MANAGEMENT" >> "$REPORT_FILE"
echo "------------------------" >> "$REPORT_FILE"
if [ -f "$LOG_DIR/disk-cleanup.log" ]; then
    TODAY=$(date +%Y-%m-%d)
    CLEANUPS=$(grep "$TODAY" "$LOG_DIR/disk-cleanup.log" 2>/dev/null | wc -l)
    echo "Cleanups performed today: $CLEANUPS" >> "$REPORT_FILE"
    if [ "$CLEANUPS" -gt 0 ]; then
        echo "Last cleanup:" >> "$REPORT_FILE"
        grep "$TODAY" "$LOG_DIR/disk-cleanup.log" 2>/dev/null | tail -1 >> "$REPORT_FILE"
    fi
else
    echo "No cleanups needed today." >> "$REPORT_FILE"
fi

# Current disk usage
CURRENT_USAGE=$(df / | tail -1 | awk '{print $5}')
echo "Current disk usage: $CURRENT_USAGE" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# 4. Heartbeat Summary (Daily Batch Review)
echo "💓 HEARTBEAT SUMMARY (Daily Review)" >> "$REPORT_FILE"
echo "------------------------------------" >> "$REPORT_FILE"
TODAY=$(date +%Y-%m-%d)

# Count heartbeats from log
if [ -f "$LOG_DIR/heartbeat-daily.log" ]; then
    HEARTBEATS=$(grep "$TODAY" "$LOG_DIR/heartbeat-daily.log" 2>/dev/null | wc -l)
    echo "Heartbeats today: $HEARTBEATS" >> "$REPORT_FILE"
    
    # Count issues
    HB_ISSUES=$(grep "$TODAY" "$LOG_DIR/heartbeat-daily.log" 2>/dev/null | grep -c "ALERT" || echo "0")
    echo "Issues found: $HB_ISSUES" >> "$REPORT_FILE"
    
    # Calculate efficiency
    if [ "$HEARTBEATS" -gt 0 ]; then
        EFFICIENCY=$(echo "scale=1; 100 - ($HB_ISSUES * 100 / $HEARTBEATS)" | bc 2>/dev/null || echo "100")
        echo "Efficiency: ${EFFICIENCY}%" >> "$REPORT_FILE"
    fi
    
    # Recent alerts if any
    if [ "$HB_ISSUES" -gt 0 ]; then
        echo "Recent alerts:" >> "$REPORT_FILE"
        grep "$TODAY" "$LOG_DIR/heartbeat-daily.log" 2>/dev/null | grep "ALERT" | tail -3 >> "$REPORT_FILE"
    fi
else
    echo "No heartbeat data logged." >> "$REPORT_FILE"
fi
echo "Note: Heartbeats collected every 30 min, reviewed daily (token efficient)" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# 5. Agent Activity Summary
echo "👤 AGENT ACTIVITY SUMMARY" >> "$REPORT_FILE"
echo "-------------------------" >> "$REPORT_FILE"
AGENT_DIR="/home/ubuntu/.openclaw/workspace/agent-agency/agents"
if [ -d "$AGENT_DIR" ]; then
    for agent_file in "$AGENT_DIR"/*/identity.yaml; do
        if [ -f "$agent_file" ]; then
            agent_id=$(grep "^agent_id:" "$agent_file" | cut -d: -f2 | xargs)
            echo "- $agent_id: Active" >> "$REPORT_FILE"
        fi
    done
fi
echo "" >> "$REPORT_FILE"

# 6. Today's Alerts to Can
echo "📤 ESCALATIONS TO CAN" >> "$REPORT_FILE"
echo "---------------------" >> "$REPORT_FILE"
if [ -f "$LOG_DIR/escalations.log" ]; then
    TODAY=$(date +%Y-%m-%d)
    ESCALATIONS=$(grep "$TODAY" "$LOG_DIR/escalations.log" 2>/dev/null | wc -l)
    echo "Total escalations today: $ESCALATIONS" >> "$REPORT_FILE"
    if [ "$ESCALATIONS" -gt 0 ]; then
        echo "Summary:" >> "$REPORT_FILE"
        grep "$TODAY" "$LOG_DIR/escalations.log" 2>/dev/null | tail -3 >> "$REPORT_FILE"
    fi
else
    echo "No escalations today." >> "$REPORT_FILE"
fi
echo "" >> "$REPORT_FILE"

# 7. System Health Status
echo "🏥 SYSTEM HEALTH STATUS" >> "$REPORT_FILE"
echo "-----------------------" >> "$REPORT_FILE"
echo "Immune System: OPERATIONAL ✅" >> "$REPORT_FILE"
echo "Policy Engine: OPERATIONAL ✅" >> "$REPORT_FILE"
echo "Audit Logging: OPERATIONAL ✅" >> "$REPORT_FILE"
echo "Disk Monitor: OPERATIONAL ✅" >> "$REPORT_FILE"
echo "Heartbeat Inspector: OPERATIONAL ✅" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# 8. Recommendations
echo "💡 RECOMMENDATIONS" >> "$REPORT_FILE"
echo "------------------" >> "$REPORT_FILE"
if [ "$BLOCKED" -gt 5 ]; then
    echo "- High number of blocked actions. Review policies." >> "$REPORT_FILE"
fi
if [ "$CURRENT_USAGE" ">" "90%" ]; then
    echo "- Disk usage critical. Manual cleanup recommended." >> "$REPORT_FILE"
fi
if [ "$ISSUES" -gt 0 ]; then
    echo "- Heartbeat issues detected. Review laziness engine." >> "$REPORT_FILE"
fi
echo "- System stable. No immediate action required." >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

echo "========================================" >> "$REPORT_FILE"
echo "End of Report" >> "$REPORT_FILE"
echo "Generated by Alex 🛡️ Immune System" >> "$REPORT_FILE"

# Output the report
cat "$REPORT_FILE"

# Clean up
rm -f "$REPORT_FILE"
